server:
  port: 777
gateway-server:
  serverName: test-provider
  center-addr: 127.0.0.1:18080
  safeKey: safeKey
  safeSecret: safeSecret
spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379